set_property PACKAGE_PIN N16 [get_ports sys_rst_n]
set_property PACKAGE_PIN Y11 [get_ports {dac_data1[13]}]
set_property PACKAGE_PIN W11 [get_ports {dac_data1[12]}]
set_property PACKAGE_PIN Y13 [get_ports {dac_data1[11]}]
set_property PACKAGE_PIN Y12 [get_ports {dac_data1[10]}]
set_property PACKAGE_PIN V11 [get_ports {dac_data1[9]}]
set_property PACKAGE_PIN V10 [get_ports {dac_data1[8]}]
set_property PACKAGE_PIN W10 [get_ports {dac_data1[7]}]
set_property PACKAGE_PIN W9 [get_ports {dac_data1[6]}]
set_property PACKAGE_PIN Y9 [get_ports {dac_data1[5]}]
set_property PACKAGE_PIN Y8 [get_ports {dac_data1[4]}]
set_property PACKAGE_PIN Y7 [get_ports {dac_data1[3]}]
set_property PACKAGE_PIN Y6 [get_ports {dac_data1[2]}]
set_property PACKAGE_PIN W6 [get_ports {dac_data1[1]}]
set_property PACKAGE_PIN V6 [get_ports {dac_data1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in_50M]
set_property IOSTANDARD LVCMOS33 [get_ports dac_clk1]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[0]}]

set_property SLEW FAST [get_ports {dac_data1[13]}]
set_property SLEW FAST [get_ports {dac_data1[12]}]
set_property SLEW FAST [get_ports {dac_data1[11]}]
set_property SLEW FAST [get_ports {dac_data1[10]}]
set_property SLEW FAST [get_ports {dac_data1[9]}]
set_property SLEW FAST [get_ports {dac_data1[8]}]
set_property SLEW FAST [get_ports {dac_data1[7]}]
set_property SLEW FAST [get_ports {dac_data1[6]}]
set_property SLEW FAST [get_ports {dac_data1[5]}]
set_property SLEW FAST [get_ports {dac_data1[4]}]
set_property SLEW FAST [get_ports {dac_data1[3]}]
set_property SLEW FAST [get_ports {dac_data1[2]}]
set_property SLEW FAST [get_ports {dac_data1[1]}]
set_property SLEW FAST [get_ports {dac_data1[0]}]
set_property SLEW FAST [get_ports dac_clk1]
set_property PACKAGE_PIN U18 [get_ports clk_in_50M]

set_property PACKAGE_PIN T11 [get_ports clk_2_5M]
set_property PACKAGE_PIN V5 [get_ports clk_200K]
set_property PACKAGE_PIN T9 [get_ports dac_clk1]
set_property PACKAGE_PIN L14 [get_ports start_key]
set_property IOSTANDARD LVCMOS33 [get_ports clk_2_5M]
set_property IOSTANDARD LVCMOS33 [get_ports clk_200K]
set_property IOSTANDARD LVCMOS33 [get_ports start_key]

set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports pulse_16ms_1ms]
set_property PACKAGE_PIN V12 [get_ports {data[3]}]
set_property PACKAGE_PIN V13 [get_ports {data[2]}]
set_property PACKAGE_PIN U13 [get_ports {data[1]}]
set_property PACKAGE_PIN U14 [get_ports {data[0]}]
set_property PACKAGE_PIN U15 [get_ports hsync]
set_property PACKAGE_PIN U10 [get_ports pulse_16ms_1ms]
set_property PACKAGE_PIN W13 [get_ports en]

## LCD R
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {lcd_r[0]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports {lcd_r[1]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {lcd_r[2]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {lcd_r[3]}]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {lcd_r[4]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {lcd_r[5]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {lcd_r[6]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {lcd_r[7]}]

## LCD G
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {lcd_g[0]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {lcd_g[1]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports {lcd_g[2]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {lcd_g[3]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {lcd_g[4]}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {lcd_g[5]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {lcd_g[6]}]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports {lcd_g[7]}]

## LCD B
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {lcd_b[0]}]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {lcd_b[1]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {lcd_b[2]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {lcd_b[3]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports {lcd_b[4]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports {lcd_b[5]}]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {lcd_b[6]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {lcd_b[7]}]

## LCD 控制信号
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports lcd_hsync]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports lcd_vsync]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports lcd_de]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports lcd_bl]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports lcd_pclk]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports lcd_rst]

set_property -dict {PACKAGE_PIN T5 IOSTANDARD LVCMOS33} [get_ports clk_row]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS33} [get_ports read_enable]
set_property -dict {PACKAGE_PIN U7 IOSTANDARD LVCMOS33} [get_ports row_0]
set_property -dict {PACKAGE_PIN V7 IOSTANDARD LVCMOS33} [get_ports row_127]
set_property -dict {PACKAGE_PIN V8 IOSTANDARD LVCMOS33} [get_ports {vout[0]}]
set_property -dict {PACKAGE_PIN W8 IOSTANDARD LVCMOS33} [get_ports {vout[1]}]
set_property -dict {PACKAGE_PIN U8 IOSTANDARD LVCMOS33} [get_ports {vout[2]}]
set_property -dict {PACKAGE_PIN U9 IOSTANDARD LVCMOS33} [get_ports {vout[3]}]
set_property PACKAGE_PIN J15 [get_ports uart_tx_o]
set_property IOSTANDARD LVCMOS33 [get_ports uart_tx_o]
set_property PACKAGE_PIN K16 [get_ports key_snapshot]
set_property IOSTANDARD LVCMOS33 [get_ports key_snapshot]
