set_property PACKAGE_PIN N16 [get_ports sys_rst_n]
set_property PACKAGE_PIN T5 [get_ports {dac_data1[11]}]
set_property PACKAGE_PIN V7 [get_ports {dac_data1[10]}]
set_property PACKAGE_PIN U7 [get_ports {dac_data1[9]}]
set_property PACKAGE_PIN W8 [get_ports {dac_data1[8]}]
set_property PACKAGE_PIN V8 [get_ports {dac_data1[7]}]
set_property PACKAGE_PIN U9 [get_ports {dac_data1[6]}]
set_property PACKAGE_PIN U8 [get_ports {dac_data1[5]}]
set_property PACKAGE_PIN U10 [get_ports {dac_data1[4]}]
set_property PACKAGE_PIN T9 [get_ports {dac_data1[3]}]
set_property PACKAGE_PIN W6 [get_ports {dac_data1[2]}]
set_property PACKAGE_PIN V6 [get_ports {dac_data1[1]}]
set_property PACKAGE_PIN Y7 [get_ports {dac_data1[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in_50M]
set_property IOSTANDARD LVCMOS33 [get_ports dac_clk1]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dac_data1[0]}]

set_property SLEW FAST [get_ports {dac_data1[11]}]
set_property SLEW FAST [get_ports {dac_data1[10]}]
set_property SLEW FAST [get_ports {dac_data1[9]}]
set_property SLEW FAST [get_ports {dac_data1[8]}]
set_property SLEW FAST [get_ports {dac_data1[7]}]
set_property SLEW FAST [get_ports {dac_data1[6]}]
set_property SLEW FAST [get_ports {dac_data1[5]}]
set_property SLEW FAST [get_ports {dac_data1[4]}]
set_property SLEW FAST [get_ports {dac_data1[3]}]
set_property SLEW FAST [get_ports {dac_data1[2]}]
set_property SLEW FAST [get_ports {dac_data1[1]}]
set_property SLEW FAST [get_ports {dac_data1[0]}]
set_property SLEW FAST [get_ports dac_clk1]

set_property PACKAGE_PIN U18 [get_ports clk_in_50M]

##改
set_property PACKAGE_PIN Y9 [get_ports clk_2_5M]

set_property PACKAGE_PIN Y8 [get_ports clk_200K]
set_property PACKAGE_PIN W10 [get_ports dac_clk1]
set_property PACKAGE_PIN L14 [get_ports start_key]
set_property IOSTANDARD LVCMOS33 [get_ports clk_2_5M]
set_property IOSTANDARD LVCMOS33 [get_ports clk_200K]
set_property IOSTANDARD LVCMOS33 [get_ports start_key]

set_property IOSTANDARD LVCMOS33 [get_ports {data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports hsync]
set_property IOSTANDARD LVCMOS33 [get_ports pulse_16ms_1ms]
set_property PACKAGE_PIN W11 [get_ports {data[3]}]
set_property PACKAGE_PIN V13 [get_ports {data[2]}]
set_property PACKAGE_PIN U13 [get_ports {data[1]}]
set_property PACKAGE_PIN U14 [get_ports {data[0]}]
set_property PACKAGE_PIN U15 [get_ports hsync]
set_property PACKAGE_PIN V12 [get_ports pulse_16ms_1ms]
set_property PACKAGE_PIN W13 [get_ports en]

set_property MARK_DEBUG true [get_nets {data_ila[0]}]
set_property MARK_DEBUG true [get_nets {data_ila[1]}]
set_property MARK_DEBUG true [get_nets {data_ila[2]}]
set_property MARK_DEBUG true [get_nets {data_ila[3]}]
set_property MARK_DEBUG true [get_nets en_ila]

connect_debug_port u_ila_0/clk [get_nets [list instance_name/inst/clk_out1]]
connect_debug_port u_ila_0/probe0 [get_nets [list {data_ila[0]} {data_ila[1]} {data_ila[2]} {data_ila[3]}]]
connect_debug_port u_ila_0/probe1 [get_nets [list {wave_start_en_shift[0]} {wave_start_en_shift[1]} {wave_start_en_shift[2]} {wave_start_en_shift[3]} {wave_start_en_shift[4]} {wave_start_en_shift[5]} {wave_start_en_shift[6]} {wave_start_en_shift[7]}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {pulse_16ms_1ms_cnt[0]} {pulse_16ms_1ms_cnt[1]} {pulse_16ms_1ms_cnt[2]} {pulse_16ms_1ms_cnt[3]} {pulse_16ms_1ms_cnt[4]} {pulse_16ms_1ms_cnt[5]} {pulse_16ms_1ms_cnt[6]} {pulse_16ms_1ms_cnt[7]} {pulse_16ms_1ms_cnt[8]} {pulse_16ms_1ms_cnt[9]} {pulse_16ms_1ms_cnt[10]} {pulse_16ms_1ms_cnt[11]} {pulse_16ms_1ms_cnt[12]} {pulse_16ms_1ms_cnt[13]} {pulse_16ms_1ms_cnt[14]} {pulse_16ms_1ms_cnt[15]} {pulse_16ms_1ms_cnt[16]}]]
connect_debug_port u_ila_0/probe3 [get_nets [list {state[0]} {state[1]} {state[2]} {state[3]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {start_key_delay_shift[0]} {start_key_delay_shift[1]} {start_key_delay_shift[2]} {start_key_delay_shift[3]} {start_key_delay_shift[4]} {start_key_delay_shift[5]} {start_key_delay_shift[6]} {start_key_delay_shift[7]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {clk_cnt[0]} {clk_cnt[1]} {clk_cnt[2]} {clk_cnt[3]} {clk_cnt[4]} {clk_cnt[5]} {clk_cnt[6]} {clk_cnt[7]} {clk_cnt[8]} {clk_cnt[9]} {clk_cnt[10]} {clk_cnt[11]} {clk_cnt[12]} {clk_cnt[13]} {clk_cnt[14]} {clk_cnt[15]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {cycle_7_cnt[0]} {cycle_7_cnt[1]} {cycle_7_cnt[2]} {cycle_7_cnt[3]} {cycle_7_cnt[4]} {cycle_7_cnt[5]} {cycle_7_cnt[6]} {cycle_7_cnt[7]} {cycle_7_cnt[8]} {cycle_7_cnt[9]} {cycle_7_cnt[10]} {cycle_7_cnt[11]} {cycle_7_cnt[12]} {cycle_7_cnt[13]} {cycle_7_cnt[14]} {cycle_7_cnt[15]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {cycle_89_cnt[0]} {cycle_89_cnt[1]} {cycle_89_cnt[2]} {cycle_89_cnt[3]} {cycle_89_cnt[4]} {cycle_89_cnt[5]} {cycle_89_cnt[6]} {cycle_89_cnt[7]} {cycle_89_cnt[8]} {cycle_89_cnt[9]} {cycle_89_cnt[10]} {cycle_89_cnt[11]} {cycle_89_cnt[12]} {cycle_89_cnt[13]} {cycle_89_cnt[14]} {cycle_89_cnt[15]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {dac_data[0]} {dac_data[1]} {dac_data[2]} {dac_data[3]} {dac_data[4]} {dac_data[5]} {dac_data[6]} {dac_data[7]} {dac_data[8]} {dac_data[9]} {dac_data[10]} {dac_data[11]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list en_ila]]
connect_debug_port u_ila_0/probe12 [get_nets [list hsync_ila]]
connect_debug_port u_ila_0/probe13 [get_nets [list working_state]]
connect_debug_port dbg_hub/clk [get_nets clk_5M]

## LCD R
set_property -dict {PACKAGE_PIN V16 IOSTANDARD LVCMOS33} [get_ports {lcd_r[0]}]
set_property -dict {PACKAGE_PIN W16 IOSTANDARD LVCMOS33} [get_ports {lcd_r[1]}]
set_property -dict {PACKAGE_PIN T14 IOSTANDARD LVCMOS33} [get_ports {lcd_r[2]}]
set_property -dict {PACKAGE_PIN T15 IOSTANDARD LVCMOS33} [get_ports {lcd_r[3]}]
set_property -dict {PACKAGE_PIN Y17 IOSTANDARD LVCMOS33} [get_ports {lcd_r[4]}]
set_property -dict {PACKAGE_PIN Y16 IOSTANDARD LVCMOS33} [get_ports {lcd_r[5]}]
set_property -dict {PACKAGE_PIN T16 IOSTANDARD LVCMOS33} [get_ports {lcd_r[6]}]
set_property -dict {PACKAGE_PIN U17 IOSTANDARD LVCMOS33} [get_ports {lcd_r[7]}]

## LCD G
set_property -dict {PACKAGE_PIN V17 IOSTANDARD LVCMOS33} [get_ports {lcd_g[0]}]
set_property -dict {PACKAGE_PIN V18 IOSTANDARD LVCMOS33} [get_ports {lcd_g[1]}]
set_property -dict {PACKAGE_PIN T17 IOSTANDARD LVCMOS33} [get_ports {lcd_g[2]}]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports {lcd_g[3]}]
set_property -dict {PACKAGE_PIN Y18 IOSTANDARD LVCMOS33} [get_ports {lcd_g[4]}]
set_property -dict {PACKAGE_PIN Y19 IOSTANDARD LVCMOS33} [get_ports {lcd_g[5]}]
set_property -dict {PACKAGE_PIN P15 IOSTANDARD LVCMOS33} [get_ports {lcd_g[6]}]
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports {lcd_g[7]}]

## LCD B
set_property -dict {PACKAGE_PIN W18 IOSTANDARD LVCMOS33} [get_ports {lcd_b[0]}]
set_property -dict {PACKAGE_PIN W19 IOSTANDARD LVCMOS33} [get_ports {lcd_b[1]}]
set_property -dict {PACKAGE_PIN R16 IOSTANDARD LVCMOS33} [get_ports {lcd_b[2]}]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports {lcd_b[3]}]
set_property -dict {PACKAGE_PIN W20 IOSTANDARD LVCMOS33} [get_ports {lcd_b[4]}]
set_property -dict {PACKAGE_PIN V20 IOSTANDARD LVCMOS33} [get_ports {lcd_b[5]}]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports {lcd_b[6]}]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports {lcd_b[7]}]

## LCD 控制信号
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports lcd_hsync]
set_property -dict {PACKAGE_PIN T20 IOSTANDARD LVCMOS33} [get_ports lcd_vsync]
set_property -dict {PACKAGE_PIN U20 IOSTANDARD LVCMOS33} [get_ports lcd_de]
set_property -dict {PACKAGE_PIN M20 IOSTANDARD LVCMOS33} [get_ports lcd_bl]
set_property -dict {PACKAGE_PIN P19 IOSTANDARD LVCMOS33} [get_ports lcd_pclk]
set_property -dict {PACKAGE_PIN L17 IOSTANDARD LVCMOS33} [get_ports lcd_rst]



set_property -dict {PACKAGE_PIN V11 IOSTANDARD LVCMOS33} [get_ports read_enable]

set_property -dict {PACKAGE_PIN V10 IOSTANDARD LVCMOS33} [get_ports {vout[0]}]
set_property -dict {PACKAGE_PIN Y13 IOSTANDARD LVCMOS33} [get_ports {vout[1]}]
set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS33} [get_ports {vout[2]}]
set_property -dict {PACKAGE_PIN Y11 IOSTANDARD LVCMOS33} [get_ports {vout[3]}]




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list u_wave_top/instance_name/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 16 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {u_wave_top/cycle_89_cnt[0]} {u_wave_top/cycle_89_cnt[1]} {u_wave_top/cycle_89_cnt[2]} {u_wave_top/cycle_89_cnt[3]} {u_wave_top/cycle_89_cnt[4]} {u_wave_top/cycle_89_cnt[5]} {u_wave_top/cycle_89_cnt[6]} {u_wave_top/cycle_89_cnt[7]} {u_wave_top/cycle_89_cnt[8]} {u_wave_top/cycle_89_cnt[9]} {u_wave_top/cycle_89_cnt[10]} {u_wave_top/cycle_89_cnt[11]} {u_wave_top/cycle_89_cnt[12]} {u_wave_top/cycle_89_cnt[13]} {u_wave_top/cycle_89_cnt[14]} {u_wave_top/cycle_89_cnt[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 16 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {u_wave_top/clk_cnt[0]} {u_wave_top/clk_cnt[1]} {u_wave_top/clk_cnt[2]} {u_wave_top/clk_cnt[3]} {u_wave_top/clk_cnt[4]} {u_wave_top/clk_cnt[5]} {u_wave_top/clk_cnt[6]} {u_wave_top/clk_cnt[7]} {u_wave_top/clk_cnt[8]} {u_wave_top/clk_cnt[9]} {u_wave_top/clk_cnt[10]} {u_wave_top/clk_cnt[11]} {u_wave_top/clk_cnt[12]} {u_wave_top/clk_cnt[13]} {u_wave_top/clk_cnt[14]} {u_wave_top/clk_cnt[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {u_wave_top/cycle_7_cnt[0]} {u_wave_top/cycle_7_cnt[1]} {u_wave_top/cycle_7_cnt[2]} {u_wave_top/cycle_7_cnt[3]} {u_wave_top/cycle_7_cnt[4]} {u_wave_top/cycle_7_cnt[5]} {u_wave_top/cycle_7_cnt[6]} {u_wave_top/cycle_7_cnt[7]} {u_wave_top/cycle_7_cnt[8]} {u_wave_top/cycle_7_cnt[9]} {u_wave_top/cycle_7_cnt[10]} {u_wave_top/cycle_7_cnt[11]} {u_wave_top/cycle_7_cnt[12]} {u_wave_top/cycle_7_cnt[13]} {u_wave_top/cycle_7_cnt[14]} {u_wave_top/cycle_7_cnt[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 12 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {u_wave_top/dac_data[0]} {u_wave_top/dac_data[1]} {u_wave_top/dac_data[2]} {u_wave_top/dac_data[3]} {u_wave_top/dac_data[4]} {u_wave_top/dac_data[5]} {u_wave_top/dac_data[6]} {u_wave_top/dac_data[7]} {u_wave_top/dac_data[8]} {u_wave_top/dac_data[9]} {u_wave_top/dac_data[10]} {u_wave_top/dac_data[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 4 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {u_wave_top/state[0]} {u_wave_top/state[1]} {u_wave_top/state[2]} {u_wave_top/state[3]}]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list u_wave_top/instance_name/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 8 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {u_wave_top/wave_start_en_shift[0]} {u_wave_top/wave_start_en_shift[1]} {u_wave_top/wave_start_en_shift[2]} {u_wave_top/wave_start_en_shift[3]} {u_wave_top/wave_start_en_shift[4]} {u_wave_top/wave_start_en_shift[5]} {u_wave_top/wave_start_en_shift[6]} {u_wave_top/wave_start_en_shift[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 4 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {u_wave_top/data_ila[0]} {u_wave_top/data_ila[1]} {u_wave_top/data_ila[2]} {u_wave_top/data_ila[3]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 17 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {u_wave_top/pulse_16ms_1ms_cnt[0]} {u_wave_top/pulse_16ms_1ms_cnt[1]} {u_wave_top/pulse_16ms_1ms_cnt[2]} {u_wave_top/pulse_16ms_1ms_cnt[3]} {u_wave_top/pulse_16ms_1ms_cnt[4]} {u_wave_top/pulse_16ms_1ms_cnt[5]} {u_wave_top/pulse_16ms_1ms_cnt[6]} {u_wave_top/pulse_16ms_1ms_cnt[7]} {u_wave_top/pulse_16ms_1ms_cnt[8]} {u_wave_top/pulse_16ms_1ms_cnt[9]} {u_wave_top/pulse_16ms_1ms_cnt[10]} {u_wave_top/pulse_16ms_1ms_cnt[11]} {u_wave_top/pulse_16ms_1ms_cnt[12]} {u_wave_top/pulse_16ms_1ms_cnt[13]} {u_wave_top/pulse_16ms_1ms_cnt[14]} {u_wave_top/pulse_16ms_1ms_cnt[15]} {u_wave_top/pulse_16ms_1ms_cnt[16]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 8 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {u_wave_top/start_key_delay_shift[0]} {u_wave_top/start_key_delay_shift[1]} {u_wave_top/start_key_delay_shift[2]} {u_wave_top/start_key_delay_shift[3]} {u_wave_top/start_key_delay_shift[4]} {u_wave_top/start_key_delay_shift[5]} {u_wave_top/start_key_delay_shift[6]} {u_wave_top/start_key_delay_shift[7]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 1 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list u_wave_top/clk_2_5M]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 1 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list u_wave_top/clk_200K]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 1 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list u_wave_top/en_ila]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list u_wave_top/hsync_ila]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe8]
set_property port_width 1 [get_debug_ports u_ila_1/probe8]
connect_debug_port u_ila_1/probe8 [get_nets [list u_wave_top/working_state]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_1_clk_out1]
